
script:
 - curl -X POST ${DOCKER_HUB_TRIGGER_URL}
# TODO add a small functional test for all images before triggering docker hub?
# Build images locally before? Or use latest versions from docker hub?
# If build, why not push them from here?
# `SKIP_PUSH=true hooks/build`