
script:
 - chmod +x hooks/build
 - chmod +x test/smoketest.sh

# Simple smoke test for all images before triggering docker hub
# We could as well push our images from here to DockerHub?!
 - SKIP_PUSH=true hooks/build
 - test/smoketest.sh schnatterer/fernflower:native
 - test/smoketest.sh schnatterer/fernflower:jre
 - test/smoketest.sh schnatterer/fernflower:alpine-jre
 - test/smoketest.sh schnatterer/fernflower:distroless
 - curl -X POST ${DOCKER_HUB_TRIGGER_URL}