#!/bin/bash
set -ex

# Don't use docker cloud build's IMAGE_NAME, because it already contains the tag latest.
IMAGE_NAME=schnatterer/fernflower

function main() {

    init

    build 'native-graalvm19'
    tag 'native-graalvm19' 'latest'
    tag 'native-graalvm19' 'native'
    tag 'native-graalvm19' "native-${GIT_SHA1_SHORT}"
    tag 'native-graalvm19' "${GIT_SHA1_SHORT}"

    build 'jdk8'
    tag 'jdk8' 'jdk8'
    tag 'jdk8' 'jre'
    tag 'jdk8' "jre-${GIT_SHA1_SHORT}"

    createJdkDockerfileWithDifferentImage '../alpine-jre-jdk8' 'adoptopenjdk\/openjdk8:alpine-jre'
    build 'alpine-jre-jdk8'
    tag 'alpine-jre-jdk8' 'alpine-jre-jdk8'
    tag 'alpine-jre-jdk8' 'alpine-jre'
    tag 'alpine-jre-jdk8' "alpine-jre-${GIT_SHA1_SHORT}"

    createJdkDockerfileWithDifferentImage '../distroless-jdk8' 'gcr.io\/distroless\/java:8'
    build 'distroless-jdk8'
    tag 'distroless-jdk8' 'distroless-jdk8'
    tag 'distroless-jdk8' 'distroless'
    tag 'distroless-jdk8' "distroless-${GIT_SHA1_SHORT}"

    cd ..
    git clean -fd
}

function init() {
    rm -rf fernflower

    git clean -fd
    git clone https://github.com/fesh0r/fernflower

    GIT_SHA1=$(cd fernflower && git rev-parse HEAD)
    GIT_SHA1_SHORT=$(cd fernflower && git rev-parse --short HEAD)

    GIT_TAG=GIT_SHA1
    POTENTIAL_TAG=$(git name-rev --name-only --tags HEAD)
    if [ "${POTENTIAL_TAG}" != "undefined" ]; then
        GIT_TAG="${POTENTIAL_TAG}"
    fi

    cd fernflower
}

function createJdkDockerfileWithDifferentImage() {
    local FOLDER="$1"
    local IMAGE="$2"
    cp -r ../jdk8 ${FOLDER}
    sed -i "s/adoptopenjdk\/openjdk8:jre/${IMAGE}/" ${FOLDER}/Dockerfile
}

function build() {
    local TAG="$1"

    cp -f ../${TAG}/Dockerfile .
    docker image build \
        --build-arg VCS_REF="${GIT_SHA1}" \
        --build-arg SOURCE_REPOSITORY_URL="${SOURCE_REPOSITORY_URL}" \
        --build-arg GIT_TAG="${GIT_TAG}" \
        --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
        --tag ${IMAGE_NAME}:${TAG}-${GIT_SHA1_SHORT} \
        .

    push "${IMAGE_NAME}:${TAG}-${GIT_SHA1_SHORT}"
}

function tag() {
   local SRC="$1"
   local TARGET="$2"
   docker tag ${IMAGE_NAME}:${SRC}-${GIT_SHA1_SHORT} ${IMAGE_NAME}:${TARGET}
   push "${IMAGE_NAME}:${TARGET}"
}

function push() {
    if [ "${SKIP_PUSH}" = true ] ; then
        echo "Skipping push, because SKIP_PUSH set to true"
    else
        docker push "$1"
    fi
}

main "$@"